version: '3.8'
services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge