- name: Deploy to worker nodes
  hosts: front-worker
  gather_facts: false
  vars:
    release_dir: /home/ubuntu/release
    local_tmp_dir: ./tmp/release  # Changed to match the local path from previous playbook

  tasks:
    - name: Ensure release directory exists
      file:
        path: "{{ release_dir }}"
        state: directory
        mode: '0755'

    - name: Sync release files to workers
      synchronize:
        src: "{{ local_tmp_dir }}/"
        dest: "{{ release_dir }}"
        delete: yes
        mode: push  # Explicitly set to push mode to send from local to remote
      delegate_to: localhost  # Execute rsync from local machine

    - name: Set correct permissions
      file:
        path: "{{ release_dir }}"
        state: directory
        recurse: yes
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Reload application
      command: pm2 stop ecosystem.config.js --env prod
      args:
        chdir: "{{ release_dir }}"

    - name: Reload application
      command: pm2 start ecosystem.config.js --env prod
      args:
        chdir: "{{ release_dir }}"
